// # 📄 Dosya Yolu: E:/Projects/TurkuazOffice/apps/desktop/src/config/ipc-commands.ts
// # 📌 Amac: Tauri IPC command adlarini tek merkezi kontratta toplar
// # 📌 Modul - FileType: Config - TypeScript
// # Version: 0.11.0
// # Aciklama: Frontend Tool katmaninda Writer ve Sheet IPC magic string kullanilmasini engeller
// Bagimli Oldugu Katman: Config

export const IPC_COMMANDS = {
  sheetCreateDocument: "sheet_create_document",
  sheetGetDocument: "sheet_get_document",
  sheetGetEvaluatedCell: "sheet_get_evaluated_cell",
  sheetGetCellFormat: "sheet_get_cell_format",
  sheetGetRangeSummary: "sheet_get_range_summary",
  sheetCreateChart: "sheet_create_chart",
  sheetRemoveChart: "sheet_remove_chart",
  sheetGetChartData: "sheet_get_chart_data",
  sheetCreateTable: "sheet_create_table",
  sheetRemoveTable: "sheet_remove_table",
  sheetCreateConditionalFormat: "sheet_create_conditional_format",
  sheetRemoveConditionalFormat: "sheet_remove_conditional_format",
  sheetGetConditionalFormatMatches: "sheet_get_conditional_format_matches",
  sheetSetCellFormat: "sheet_set_cell_format",
  sheetQueryRows: "sheet_query_rows",
  sheetSetText: "sheet_set_text",
  sheetSetNumber: "sheet_set_number",
  sheetSetBoolean: "sheet_set_boolean",
  sheetSetFormula: "sheet_set_formula",
  sheetClearCell: "sheet_clear_cell",
  writerTakeStartupFile: "writer_take_startup_file",
  writerListRecentFiles: "writer_list_recent_files",
  writerRecordRecentFile: "writer_record_recent_file",
  writerListTemplates: "writer_list_templates",
  writerCreateDocumentFromTemplate: "writer_create_document_from_template",
  writerCreateDocument: "writer_create_document",
  writerOpenDocument: "writer_open_document",
  writerImportDocx: "writer_import_docx",
  writerExportDocx: "writer_export_docx",
  writerExportPdf: "writer_export_pdf",
  writerSaveDocument: "writer_save_document",
  writerGetFileSession: "writer_get_file_session",
  writerAcknowledgeExternalChange: "writer_acknowledge_external_change",
  writerReloadFromDisk: "writer_reload_from_disk",
  writerListRecoverySnapshots: "writer_list_recovery_snapshots",
  writerCreateRecoverySnapshot: "writer_create_recovery_snapshot",
  writerRestoreRecoverySnapshot: "writer_restore_recovery_snapshot",
  writerCompareRecoverySnapshot: "writer_compare_recovery_snapshot",
  writerDiscardRecoverySnapshot: "writer_discard_recovery_snapshot",
  writerClearDocumentRecovery: "writer_clear_document_recovery",
  writerGetAsset: "writer_get_asset",
  writerInsertImageData: "writer_insert_image_data",
  writerReplaceParagraphText: "writer_replace_paragraph_text",
  writerReplaceRangeWithStyledRuns: "writer_replace_range_with_styled_runs",
  writerReplaceAllRanges: "writer_replace_all_ranges",
  writerApplyCharacterStyle: "writer_apply_character_style",
  writerApplyParagraphAlignment: "writer_apply_paragraph_alignment",
  writerSplitParagraph: "writer_split_paragraph",
  writerMergeWithPrevious: "writer_merge_with_previous",
  writerUndo: "writer_undo",
  writerRedo: "writer_redo",
} as const;
