#!/usr/bin/env bash
# 📄 Dosya Yolu: E:/Projects/TurkuazOffice/tools/verify-project.sh
# 📌 Amac: Linux ve CI ortaminda M1 Writer, M2/R2 Sheet ve M3 Web foundation proje kontratlarini dogrular
# 📌 Modul - FileType: Tool - Shell
# Version: 0.3.2
# Aciklama: Umbrella release versionini korur; M1/M2/R2 ve M3 Web foundation static contract kontrollerini uygular
# Bagimli Oldugu Katman: Tool

set -euo pipefail

trap 'echo "verify_contract_failed line=$LINENO command=$BASH_COMMAND" >&2' ERR

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CURRENT_VERSION="0.3.1"
SHEET_MODULE_VERSION="0.3.0"

required_files=(
  "README.md"
  "CHANGELOG.md"
  "Cargo.toml"
  "rust-toolchain.toml"
  ".gitignore"
  "config/project.yml"
  "docs/README.md"
  "docs/08-implementation/m1-writer-domain-v0.2.0.md"
  "docs/08-implementation/m1-desktop-shell-v0.2.0.md"
  "docs/08-implementation/m1-rich-text-ime-v0.2.0.md"
  "docs/08-implementation/m1-rich-text-ime-validation.md"
  "docs/08-implementation/m1-typography-ribbon-v0.2.0.md"
  "docs/08-implementation/m1-typography-ribbon-validation.md"
  "docs/08-implementation/m1-local-open-save-v0.2.0.md"
  "docs/08-implementation/m1-local-open-save-validation.md"
  "docs/07-quality/local-open-save-test-matrix.md"
  "docs/06-adr/0016-tko-v1-local-safe-save.md"
  "docs/08-implementation/m1-autosave-recovery-v0.2.0.md"
  "docs/08-implementation/m1-autosave-recovery-validation.md"
  "docs/07-quality/autosave-recovery-test-matrix.md"
  "docs/06-adr/0017-autosave-recovery-snapshot.md"
  "docs/07-quality/writer-domain-test-matrix.md"
  "docs/07-quality/desktop-shell-test-matrix.md"
  "docs/07-quality/rich-text-ime-test-matrix.md"
  "docs/07-quality/typography-ribbon-test-matrix.md"
  "docs/06-adr/0010-writer-logical-offset.md"
  "docs/06-adr/0011-writer-undo-redo-baseline.md"
  "docs/06-adr/0012-solidjs-desktop-ui.md"
  "docs/06-adr/0013-desktop-ipc-thin-bridge.md"
  "docs/06-adr/0014-ime-rich-text-contenteditable.md"
  "docs/06-adr/0015-caret-typing-style-ribbon-typography.md"
  "crates/turkuaz-office-core/Cargo.toml"
  "crates/turkuaz-office-writer/Cargo.toml"
  "crates/turkuaz-office-writer/src/lib.rs"
  "crates/turkuaz-office-writer/src/services/writer_command.rs"
  "crates/turkuaz-office-writer/src/services/writer_asset_service.rs"
  "crates/turkuaz-office-writer/src/services/writer_command_service.rs"
  "crates/turkuaz-office-writer/src/services/writer_editor_service.rs"
  "crates/turkuaz-office-writer/src/services/tko_package_service.rs"
  "crates/turkuaz-office-writer/src/services/tko_package_types.rs"
  "crates/turkuaz-office-writer/src/tools/tko_archive_tool.rs"
  "crates/turkuaz-office-writer/src/tools/tko_yaml_tool.rs"
  "crates/turkuaz-office-writer/tests/tko_package_tests.rs"
  "crates/turkuaz-office-writer/src/services/writer_types.rs"
  "crates/turkuaz-office-writer/src/views/writer_view.rs"
  "apps/desktop/package.json"
  "apps/desktop/tsconfig.json"
  "apps/desktop/vite.config.ts"
  "apps/desktop/src/main.tsx"
  "apps/desktop/src/config/dom-contract.ts"
  "apps/desktop/src/config/typography.ts"
  "apps/desktop/src/config/ribbon.ts"
  "apps/desktop/src/controllers/writer.controller.ts"
  "apps/desktop/src/services/writer-session.service.ts"
  "apps/desktop/src/repositories/writer-session.repository.ts"
  "apps/desktop/src/tools/tauri-writer.tool.ts"
  "apps/desktop/src/tools/text-offset.tool.ts"
  "apps/desktop/src/tools/dom-selection.tool.ts"
  "apps/desktop/src/tools/native-file-dialog.tool.ts"
  "apps/desktop/src/config/file-format.ts"
  "apps/desktop/src/views/writer-ribbon.tsx"
  "apps/desktop/src/views/writer-shell.tsx"
  "apps/desktop/src-tauri/Cargo.toml"
  "apps/desktop/src-tauri/tauri.conf.json5"
  "apps/desktop/src-tauri/capabilities/main-capability.toml"
  "apps/desktop/src-tauri/src/controllers/writer_desktop_controller.rs"
  "apps/desktop/src-tauri/src/services/writer_desktop_service.rs"
  "apps/desktop/src-tauri/src/services/writer_storage_service.rs"
  "apps/desktop/src/views/writer-recovery-panel.tsx"
  "apps/desktop/src-tauri/src/services/writer_recovery_service.rs"
  "apps/desktop/src-tauri/src/tools/recovery_path_tool.rs"
  "apps/desktop/src-tauri/src/tools/recovery_metadata_tool.rs"
  "apps/desktop/src-tauri/src/views/recovery_dto.rs"
  "apps/desktop/src-tauri/src/tools/local_file_tool.rs"
  "apps/desktop/src-tauri/tests/writer_desktop_service_tests.rs"
  "docs/06-adr/0018-external-change-cooperative-lock.md"
  "docs/07-quality/external-change-test-matrix.md"
  "docs/08-implementation/m1-external-change-v0.2.0.md"
  "docs/08-implementation/m1-external-change-validation.md"
  "apps/desktop/src-tauri/src/services/writer_file_session_service.rs"
  "apps/desktop/src-tauri/src/tools/file_fingerprint_tool.rs"
  "apps/desktop/src-tauri/src/tools/file_lock_tool.rs"
  "apps/desktop/src-tauri/src/views/file_session_dto.rs"
  "apps/desktop/src/views/writer-file-protection-banner.tsx"
  "docs/06-adr/0019-twip-page-layout-font-fallback.md"
  "docs/07-quality/font-layout-test-matrix.md"
  "docs/08-implementation/m1-font-layout-v0.2.0.md"
  "docs/08-implementation/m1-font-layout-validation.md"
  "apps/desktop/src/config/layout.ts"
  "apps/desktop/src/services/writer-layout.service.ts"
  "apps/desktop/src/tools/font-capability.tool.ts"
  "apps/desktop/src/config/clipboard.ts"
  "apps/desktop/src/models/clipboard-model.ts"
  "apps/desktop/src/services/clipboard.service.ts"
  "apps/desktop/src/tools/clipboard.tool.ts"
  "apps/desktop/src/tools/clipboard-dom.tool.ts"
  "apps/desktop/src/tools/image-asset.tool.ts"
  "apps/desktop/src/views/writer-image.tsx"
  "apps/desktop/src/services/clipboard.service.test.ts"
  "docs/07-quality/clipboard-styled-fragment-test-matrix.md"
  "docs/08-implementation/m1-clipboard-styled-fragment-v0.2.0.md"
  "docs/08-implementation/m1-clipboard-styled-fragment-validation.md"
  "apps/desktop/src/config/print.ts"
  "apps/desktop/src/tools/print.tool.ts"
  "apps/desktop/src/tools/print.tool.test.ts"
  "apps/desktop/src/views/writer-print-preview.tsx"
  "docs/07-quality/print-preview-test-matrix.md"
  "docs/08-implementation/m1-print-preview-v0.2.0.md"
  "docs/08-implementation/m1-print-preview-validation.md"
  "crates/turkuaz-office-format-adapters/Cargo.toml"
  "crates/turkuaz-office-format-adapters/src/lib.rs"
  "crates/turkuaz-office-format-adapters/src/config/constants.rs"
  "crates/turkuaz-office-format-adapters/src/models/docx_model.rs"
  "crates/turkuaz-office-format-adapters/src/services/docx_service.rs"
  "crates/turkuaz-office-format-adapters/src/tools/docx_archive_tool.rs"
  "crates/turkuaz-office-format-adapters/src/tools/docx_xml_tool.rs"
  "crates/turkuaz-office-format-adapters/tests/docx_minimum_tests.rs"
  "apps/desktop/src-tauri/src/services/writer_docx_service.rs"
  "apps/desktop/src-tauri/src/views/docx_dto.rs"
  "apps/desktop/src-tauri/tests/writer_docx_service_tests.rs"
  "apps/desktop/src/config/docx.ts"
  "apps/desktop/src/views/writer-docx-compatibility-banner.tsx"
  "docs/07-quality/docx-minimum-test-matrix.md"
  "docs/08-implementation/m1-docx-minimum-v0.2.0.md"
  "docs/08-implementation/m1-docx-minimum-validation.md"
  "crates/turkuaz-office-format-adapters/src/config/pdf_constants.rs"
  "crates/turkuaz-office-format-adapters/src/models/pdf_model.rs"
  "crates/turkuaz-office-format-adapters/src/services/pdf_service.rs"
  "crates/turkuaz-office-format-adapters/src/tools/pdf_writer_tool.rs"
  "crates/turkuaz-office-format-adapters/tests/pdf_minimum_tests.rs"
  "apps/desktop/src-tauri/src/services/writer_pdf_service.rs"
  "apps/desktop/src-tauri/src/config/pdf_font_config.rs"
  "apps/desktop/src-tauri/src/tools/system_font_tool.rs"
  "apps/desktop/src-tauri/tests/writer_pdf_service_tests.rs"
  "docs/07-quality/pdf-export-test-matrix.md"
  "docs/08-implementation/m1-pdf-export-v0.2.0.md"
  "docs/08-implementation/m1-pdf-export-validation.md"
  "apps/desktop/src-tauri/src/tools/app_state_path_tool.rs"
  "apps/desktop/src-tauri/src/tools/recent_files_metadata_tool.rs"
  "apps/desktop/src-tauri/src/repositories/mod.rs"
  "apps/desktop/src-tauri/src/repositories/recent_files_repository.rs"
  "apps/desktop/src-tauri/src/services/recent_files_service.rs"
  "apps/desktop/src-tauri/src/views/recent_file_dto.rs"
  "apps/desktop/src-tauri/tests/recent_files_service_tests.rs"
  "apps/desktop/src-tauri/tests/writer_recent_files_integration_tests.rs"
  "apps/desktop/src/config/recent-files.ts"
  "docs/07-quality/recent-files-test-matrix.md"
  "docs/08-implementation/m1-recent-files-v0.2.0.md"
  "docs/08-implementation/m1-recent-files-validation.md"
  "apps/desktop/src-tauri/src/tools/startup_arguments_tool.rs"
  "apps/desktop/src-tauri/src/services/startup_file_service.rs"
  "apps/desktop/src-tauri/tests/startup_file_service_tests.rs"
  "docs/07-quality/file-associations-test-matrix.md"
  "docs/08-implementation/m1-file-associations-v0.2.0.md"
  "docs/08-implementation/m1-file-associations-validation.md"
  "crates/turkuaz-office-writer/templates/builtin.yml"
  "crates/turkuaz-office-writer/src/tools/writer_template_catalog_tool.rs"
  "crates/turkuaz-office-writer/src/services/writer_template_service.rs"
  "crates/turkuaz-office-writer/tests/writer_template_tests.rs"
  "apps/desktop/src-tauri/src/views/template_dto.rs"
  "apps/desktop/src-tauri/tests/writer_template_desktop_tests.rs"
  "docs/07-quality/template-foundation-test-matrix.md"
  "docs/08-implementation/m1-template-foundation-v0.2.0.md"
  "docs/08-implementation/m1-template-foundation-validation.md"
  "apps/desktop/src/config/localization.ts"
  "apps/desktop/src/language/en.ts"
  "apps/desktop/src/language/language-packs.ts"
  "apps/desktop/src/tools/language-preference.tool.ts"
  "apps/desktop/src/services/language-preference.service.ts"
  "apps/desktop/src/language/language-service.test.ts"
  "apps/desktop/src/services/language-preference.service.test.ts"
  "docs/07-quality/turkish-english-ui-test-matrix.md"
  "docs/08-implementation/m1-turkish-english-ui-v0.2.0.md"
  "docs/08-implementation/m1-turkish-english-ui-validation.md"
  "apps/desktop/src/services/keyboard-shortcut.service.ts"
  "apps/desktop/src/services/keyboard-shortcut.service.test.ts"
  "docs/07-quality/keyboard-only-smoke-test.md"
  "docs/08-implementation/m1-keyboard-only-smoke-v0.2.0.md"
  "docs/08-implementation/m1-keyboard-only-smoke-validation.md"
  "crates/turkuaz-office-sheet/Cargo.toml"
  "crates/turkuaz-office-sheet/src/lib.rs"
  "crates/turkuaz-office-sheet/src/config/constants.rs"
  "crates/turkuaz-office-sheet/src/controllers/sheet_controller.rs"
  "crates/turkuaz-office-sheet/src/services/sheet_types.rs"
  "crates/turkuaz-office-sheet/src/services/sheet_service.rs"
  "crates/turkuaz-office-sheet/src/repositories/sheet_document_repository.rs"
  "crates/turkuaz-office-sheet/src/tools/cell_reference_tool.rs"
  "crates/turkuaz-office-sheet/src/tools/sheet_id_tool.rs"
  "crates/turkuaz-office-sheet/src/views/sheet_view.rs"
  "crates/turkuaz-office-sheet/src/language/mod.rs"
  "crates/turkuaz-office-sheet/tests/sheet_cell_model_tests.rs"
  "docs/07-quality/sheet-cell-model-test-matrix.md"
  "docs/08-implementation/m2-sheet-cell-model-v0.3.0.md"
  "docs/08-implementation/m2-sheet-cell-model-validation.md"
  "crates/turkuaz-office-format-adapters/src/config/sheet_constants.rs"
  "crates/turkuaz-office-format-adapters/src/models/sheet_xlsx_model.rs"
  "crates/turkuaz-office-format-adapters/src/services/sheet_csv_service.rs"
  "crates/turkuaz-office-format-adapters/src/services/sheet_xlsx_service.rs"
  "crates/turkuaz-office-format-adapters/src/tools/sheet_csv_tool.rs"
  "crates/turkuaz-office-format-adapters/src/tools/sheet_xlsx_archive_tool.rs"
  "crates/turkuaz-office-format-adapters/src/tools/sheet_xlsx_xml_tool.rs"
  "crates/turkuaz-office-format-adapters/tests/sheet_csv_xlsx_tests.rs"
  "docs/07-quality/sheet-csv-xlsx-test-matrix.md"
  "docs/08-implementation/m2-sheet-csv-xlsx-v0.3.0.md"
  "docs/08-implementation/m2-sheet-csv-xlsx-validation.md"
  "crates/turkuaz-office-sheet/src/tools/formula_tool.rs"
  "crates/turkuaz-office-sheet/tests/sheet_formula_engine_tests.rs"
  "docs/06-adr/0020-sheet-basic-formula-evaluation.md"
  "docs/07-quality/sheet-formula-engine-test-matrix.md"
  "docs/08-implementation/m2-sheet-formula-engine-v0.3.0.md"
  "docs/08-implementation/m2-sheet-formula-engine-validation.md"
  "crates/turkuaz-office-sheet/tests/sheet_format_filter_sort_tests.rs"
  "docs/07-quality/sheet-format-filter-sort-test-matrix.md"
  "docs/08-implementation/m2-sheet-format-filter-sort-v0.3.0.md"
  "docs/08-implementation/m2-sheet-format-filter-sort-validation.md"
  "crates/turkuaz-office-sheet/tests/sheet_basic_charts_tests.rs"
  "docs/07-quality/sheet-basic-charts-test-matrix.md"
  "docs/08-implementation/m2-sheet-basic-charts-v0.3.0.md"
  "docs/08-implementation/m2-sheet-basic-charts-validation.md"
  "crates/turkuaz-office-sheet/tests/sheet_100k_benchmark.rs"
  "docs/07-quality/sheet-100k-benchmark-profile.md"
  "docs/08-implementation/m2-sheet-100k-benchmark-v0.3.0.md"
  "docs/08-implementation/m2-sheet-100k-benchmark-validation.md"
  "docs/08-implementation/r2-sheet-desktop-integration.md"
  "apps/web/package.json"
  "apps/web/tsconfig.json"
  "apps/web/vite.config.ts"
  "apps/web/src/main.tsx"
  "apps/web/src/controllers/web-controller.ts"
  "apps/web/src/services/web-bootstrap-service.ts"
  "apps/web/src/repositories/browser-document-index.repository.ts"
  "apps/web/src/tools/web-core-tool.ts"
  "apps/web/src/tools/web-core-tool.test.ts"
  "apps/web/src/language/tr-TR.ts"
  "crates/turkuaz-office-core/src/services/web_core_service.rs"
  "crates/turkuaz-office-core/src/views/web_core_view.rs"
  "apps/web/src/views/App.tsx"
  "docs/08-implementation/m3-web-foundation-v0.4.0.md"
  "docs/08-implementation/m3-web-wasm-core-v0.4.0.md"
  "docs/07-quality/m3-web-wasm-core-test-matrix.md"
)

for relative_path in "${required_files[@]}"; do
  if [[ ! -f "$ROOT/$relative_path" ]]; then
    echo "Eksik zorunlu dosya: $relative_path" >&2
    exit 1
  fi
done

while IFS= read -r -d '' file; do
  head_content="$(head -n 14 "$file")"
  if ! grep -q "Dosya Yolu" <<<"$head_content"; then
    echo "Header eksik: $file" >&2
    exit 1
  fi
  if ! grep -q "Version:" <<<"$head_content"; then
    echo "Version header eksik: $file" >&2
    exit 1
  fi
done < <(
  find "$ROOT" \
    -path "$ROOT/node_modules" -prune -o \
    -path "$ROOT/apps/desktop/node_modules" -prune -o \
    -path "$ROOT/apps/desktop/dist" -prune -o \
    -path "$ROOT/apps/web/node_modules" -prune -o \
    -path "$ROOT/apps/web/dist" -prune -o \
    -path "$ROOT/target" -prune -o \
    -type f \( \
      -name '*.md' -o -name '*.rs' -o -name '*.toml' -o -name '*.yml' -o -name '*.yaml' \
      -o -name '*.ps1' -o -name '*.sh' -o -name '*.ts' -o -name '*.tsx' -o -name '*.css' \
      -o -name '*.html' -o -name '*.json' -o -name '*.json5' \
    \) -print0
)

grep -q "Version:" "$ROOT/.gitignore"
grep -q "Version: $CURRENT_VERSION" "$ROOT/README.md"
grep -q "Version: $CURRENT_VERSION" "$ROOT/Cargo.toml"
grep -q "Version: $CURRENT_VERSION" "$ROOT/config/project.yml"
grep -q "Version: $CURRENT_VERSION" "$ROOT/docs/README.md"
grep -q "Version: $CURRENT_VERSION" "$ROOT/docs/05-roadmap/roadmap.md"
grep -q "Version: $CURRENT_VERSION" "$ROOT/CHANGELOG.md"
grep -q 'version = "0.3.1"' "$ROOT/Cargo.toml"
grep -q 'version: 0.3.1' "$ROOT/config/project.yml"
grep -q '"version": "0.3.1"' "$ROOT/apps/desktop/package.json"
grep -q 'version: "0.3.1"' "$ROOT/apps/desktop/src-tauri/tauri.conf.json5"
grep -q '"crates/turkuaz-office-sheet"' "$ROOT/Cargo.toml"
grep -q '"apps/desktop/src-tauri"' "$ROOT/Cargo.toml"
grep -q 'community_preview:' "$ROOT/config/project.yml"
grep -q 'release_candidate: true' "$ROOT/config/project.yml"
grep -q 'desktop_ui_integrated: true' "$ROOT/config/project.yml"
grep -q '## R2 - Sheet Desktop Integration Baseline' "$ROOT/docs/05-roadmap/roadmap.md"
grep -q 'R2 Sheet Desktop baseline' "$ROOT/README.md"
grep -q 'web_client:' "$ROOT/config/project.yml"
grep -q 'milestone: m3_foundation' "$ROOT/config/project.yml"
grep -q 'native_file_system_access: false' "$ROOT/config/project.yml"
grep -q 'metadata_index_adapter: local_storage' "$ROOT/config/project.yml"
grep -q 'document_storage_adapter: indexed_db_planned' "$ROOT/config/project.yml"
grep -q 'canonical_document_payload_in_local_storage: false' "$ROOT/config/project.yml"
grep -q 'wasm_core: compile_verified' "$ROOT/config/project.yml"
grep -q 'wasm_target: wasm32-unknown-unknown' "$ROOT/config/project.yml"
grep -q 'wasm_binding: planned' "$ROOT/config/project.yml"
grep -q '"version": "0.4.0"' "$ROOT/apps/web/package.json"
grep -q 'BrowserDocumentIndexRepository' "$ROOT/apps/web/src/repositories/browser-document-index.repository.ts"
grep -q 'WebBootstrapService' "$ROOT/apps/web/src/services/web-bootstrap-service.ts"
grep -q 'BrowserCoreContractTool' "$ROOT/apps/web/src/tools/web-core-tool.ts"
grep -q 'class WasmCoreTool' "$ROOT/apps/web/src/tools/web-core-tool.ts"
grep -q 'pub struct WebCoreService' "$ROOT/crates/turkuaz-office-core/src/services/web_core_service.rs"
grep -q 'web_core_abi_version' "$ROOT/crates/turkuaz-office-core/src/services/web_core_service.rs"
grep -q 'WASM Core Check' "$ROOT/.github/workflows/workspace-ci.yml"
grep -q 'wasm32-unknown-unknown' "$ROOT/.github/workflows/workspace-ci.yml"
grep -q '## M3 - Web v0.4.0' "$ROOT/docs/05-roadmap/roadmap.md"
grep -q 'M3 Web Foundation v0.4.0' "$ROOT/docs/08-implementation/m3-web-foundation-v0.4.0.md"
grep -q 'M3 Web WASM Core v0.4.0' "$ROOT/docs/08-implementation/m3-web-wasm-core-v0.4.0.md"
grep -q 'framework: solidjs' "$ROOT/config/project.yml"
grep -q 'canonical_state_in_frontend: false' "$ROOT/config/project.yml"
grep -q 'surface: contenteditable' "$ROOT/config/project.yml"
grep -q 'materialize_on_text_insert: true' "$ROOT/config/project.yml"
grep -q 'active_tab: home' "$ROOT/config/project.yml"
grep -q 'WRITER_PARAGRAPH_MARKER_VALUE' "$ROOT/apps/desktop/src/config/dom-contract.ts"
grep -q 'WRITER_PARAGRAPH_SELECTOR' "$ROOT/apps/desktop/src/config/dom-contract.ts"
grep -q 'WRITER_RIBBON_TABS' "$ROOT/apps/desktop/src/config/ribbon.ts"
grep -q 'focusAndRestoreParagraphSelection' "$ROOT/apps/desktop/src/tools/dom-selection.tool.ts"
grep -q 'WRITER_FONT_FAMILIES' "$ROOT/apps/desktop/src/config/typography.ts"
grep -q 'writerApplyCharacterStyle' "$ROOT/apps/desktop/src/config/ipc-commands.ts"
grep -q 'writerApplyParagraphAlignment' "$ROOT/apps/desktop/src/config/ipc-commands.ts"
grep -q 'InsertStyledText' "$ROOT/crates/turkuaz-office-writer/src/services/writer_command.rs"
grep -q 'ApplyParagraphStyle' "$ROOT/crates/turkuaz-office-writer/src/services/writer_command.rs"
grep -q 'typingStyle' "$ROOT/apps/desktop/src/repositories/writer-session.repository.ts"
grep -q 'WriterRibbon' "$ROOT/apps/desktop/src/views/writer-shell.tsx"
grep -q 'pub fn execute_batch' "$ROOT/crates/turkuaz-office-writer/src/services/writer_editor_service.rs"
grep -q 'TextOffsetTool' "$ROOT/apps/desktop/src/services/writer-session.service.ts"
grep -q 'IPC_COMMANDS' "$ROOT/apps/desktop/src/tools/tauri-writer.tool.ts"
grep -q 'capabilities: \["main-capability"\]' "$ROOT/apps/desktop/src-tauri/tauri.conf.json5"

grep -q 'package_v1:' "$ROOT/config/project.yml"
grep -q 'direct_target_truncate_allowed: false' "$ROOT/config/project.yml"
grep -q 'TKO_MANIFEST_ENTRY' "$ROOT/crates/turkuaz-office-writer/src/services/tko_package_service.rs"
grep -q 'CompressionMethod::Stored' "$ROOT/crates/turkuaz-office-writer/src/tools/tko_archive_tool.rs"
grep -q 'DirectoryEntryUnsupported' "$ROOT/crates/turkuaz-office-writer/src/tools/tko_archive_tool.rs"
grep -q 'write_safe_replace' "$ROOT/apps/desktop/src-tauri/src/tools/local_file_tool.rs"
grep -q 'writerOpenDocument' "$ROOT/apps/desktop/src/config/ipc-commands.ts"
grep -q 'writerSaveDocument' "$ROOT/apps/desktop/src/config/ipc-commands.ts"
grep -q 'confirmDiscardIfNeeded' "$ROOT/apps/desktop/src/services/writer-session.service.ts"
grep -q 'dialog:allow-message' "$ROOT/apps/desktop/src-tauri/capabilities/main-capability.toml"

grep -q 'desktop_recovery:' "$ROOT/config/project.yml"
grep -q 'overwrite_source_on_autosave: false' "$ROOT/config/project.yml"
grep -q 'writerCreateRecoverySnapshot' "$ROOT/apps/desktop/src/config/ipc-commands.ts"
grep -q 'writerRestoreRecoverySnapshot' "$ROOT/apps/desktop/src/config/ipc-commands.ts"
grep -q 'autosaveRecovery' "$ROOT/apps/desktop/src/services/writer-session.service.ts"
grep -q 'WriterRecoveryPanel' "$ROOT/apps/desktop/src/views/writer-shell.tsx"
grep -q 'TkoPackageService::serialize' "$ROOT/apps/desktop/src-tauri/src/services/writer_recovery_service.rs"
grep -q 'RECOVERY_MAX_SNAPSHOTS_PER_DOCUMENT' "$ROOT/apps/desktop/src-tauri/src/config/constants.rs"


grep -q 'desktop_file_protection:' "$ROOT/config/project.yml"
grep -q 'timestamp_only_detection: false' "$ROOT/config/project.yml"
grep -q 'backend_mutation_guard: true' "$ROOT/config/project.yml"
grep -q 'writerGetFileSession' "$ROOT/apps/desktop/src/config/ipc-commands.ts"
grep -q 'writerAcknowledgeExternalChange' "$ROOT/apps/desktop/src/config/ipc-commands.ts"
grep -q 'writerReloadFromDisk' "$ROOT/apps/desktop/src/config/ipc-commands.ts"
grep -q 'ensure_writable' "$ROOT/apps/desktop/src-tauri/src/services/writer_desktop_service.rs"
grep -q 'ExternalChangeConflict' "$ROOT/apps/desktop/src-tauri/src/services/writer_file_session_service.rs"
grep -q 'create_new(true)' "$ROOT/apps/desktop/src-tauri/src/tools/file_lock_tool.rs"
grep -q 'content_hash' "$ROOT/apps/desktop/src-tauri/src/tools/file_fingerprint_tool.rs"
grep -q 'WriterFileProtectionBanner' "$ROOT/apps/desktop/src/views/writer-shell.tsx"
grep -q 'WRITER_EXTERNAL_CHANGE_POLL_MS' "$ROOT/apps/desktop/src/config/runtime-config.ts"



grep -q 'writer_layout:' "$ROOT/config/project.yml"
grep -q 'canonical_unit: twip' "$ROOT/config/project.yml"
grep -q 'browser_dom_measurement_is_canonical: false' "$ROOT/config/project.yml"
grep -q 'WriterPageSettingsView' "$ROOT/crates/turkuaz-office-writer/src/views/writer_view.rs"
grep -q 'page_settings: WriterPageSettingsDto' "$ROOT/apps/desktop/src-tauri/src/views/writer_dto.rs"
grep -q 'TWIPS_PER_INCH' "$ROOT/apps/desktop/src/config/layout.ts"
grep -q 'WRITER_FONT_FALLBACK_PROFILES' "$ROOT/apps/desktop/src/config/layout.ts"
grep -q 'class WriterLayoutService' "$ROOT/apps/desktop/src/services/writer-layout.service.ts"
grep -q 'class FontCapabilityTool' "$ROOT/apps/desktop/src/tools/font-capability.tool.ts"
grep -q 'zoomPercent' "$ROOT/apps/desktop/src/repositories/writer-session.repository.ts"
grep -q 'controller.zoomIn' "$ROOT/apps/desktop/src/views/writer-statusbar.tsx"
grep -q 'document.pageSettings' "$ROOT/apps/desktop/src/services/writer-session.service.ts"
grep -q 'writer_view_exposes_primary_page_settings_without_pixel_conversion' "$ROOT/crates/turkuaz-office-writer/tests/writer_domain_tests.rs"


grep -q 'ReplaceRangeWithStyledRuns' "$ROOT/crates/turkuaz-office-writer/src/services/writer_command.rs"
grep -q 'InsertImageData' "$ROOT/crates/turkuaz-office-writer/src/services/writer_command.rs"
grep -q 'struct WriterAsset' "$ROOT/crates/turkuaz-office-writer/src/services/writer_types.rs"
grep -q 'TKO_ASSET_INDEX_ENTRY' "$ROOT/crates/turkuaz-office-writer/src/config/constants.rs"
grep -q 'validate_image_payload' "$ROOT/crates/turkuaz-office-writer/src/services/writer_asset_service.rs"
grep -q 'decode_assets' "$ROOT/crates/turkuaz-office-writer/src/services/tko_package_service.rs"
grep -q 'CrossParagraphFragmentReplaceNotSupported' "$ROOT/crates/turkuaz-office-writer/src/services/writer_command.rs"
grep -q 'StyledTextRun' "$ROOT/crates/turkuaz-office-writer/src/services/writer_types.rs"
grep -q 'writerReplaceRangeWithStyledRuns' "$ROOT/apps/desktop/src/config/ipc-commands.ts"
grep -q 'replaceRangeWithStyledRuns' "$ROOT/apps/desktop/src/tools/tauri-writer.tool.ts"
grep -q 'replaceSelectionWithStyledRuns' "$ROOT/apps/desktop/src/services/writer-session.service.ts"
grep -q 'replaceSelectionWithStyledRuns' "$ROOT/apps/desktop/src/controllers/writer.controller.ts"
grep -q 'copySelection' "$ROOT/apps/desktop/src/controllers/writer.controller.ts"
grep -q 'pasteSelection' "$ROOT/apps/desktop/src/controllers/writer.controller.ts"
grep -q 'WRITER_CLIPBOARD_MIME' "$ROOT/apps/desktop/src/config/clipboard.ts"
grep -q 'class ClipboardService' "$ROOT/apps/desktop/src/services/clipboard.service.ts"
grep -q 'parseInternalFragment' "$ROOT/apps/desktop/src/services/clipboard.service.ts"
grep -q 'parseHtmlFragment' "$ROOT/apps/desktop/src/services/clipboard.service.ts"
grep -q 'class ClipboardTool' "$ROOT/apps/desktop/src/tools/clipboard.tool.ts"
grep -q 'class ClipboardDomTool' "$ROOT/apps/desktop/src/tools/clipboard-dom.tool.ts"
grep -q 'WRITER_CLIPBOARD_MAX_DOM_NODES' "$ROOT/apps/desktop/src/config/clipboard.ts"
grep -q 'WRITER_CLIPBOARD_MAX_DOM_DEPTH' "$ROOT/apps/desktop/src/config/clipboard.ts"
grep -q 'limitExceeded' "$ROOT/apps/desktop/src/tools/clipboard-dom.tool.ts"
grep -q 'internal MIME has paste priority' "$ROOT/apps/desktop/src/services/clipboard.service.test.ts"
grep -q 'invalid rich payload falls back to plain text' "$ROOT/apps/desktop/src/services/clipboard.service.test.ts"
grep -q 'cut writes clipboard before atomic empty fragment replace' "$ROOT/apps/desktop/src/services/clipboard.service.test.ts"
grep -q 'image-only paste consumes default DOM paste and inserts canonical asset' "$ROOT/apps/desktop/src/services/clipboard.service.test.ts"
grep -q 'image_asset_insert_and_fetch_are_exposed_by_desktop_service' "$ROOT/apps/desktop/src-tauri/tests/writer_desktop_service_tests.rs"
grep -q 'image_insert_undo_redo_restores_asset_and_block_together' "$ROOT/crates/turkuaz-office-writer/tests/writer_domain_tests.rs"
grep -q 'image_asset_survives_save_reopen_and_lazy_fetch' "$ROOT/apps/desktop/src-tauri/tests/writer_desktop_service_tests.rs"
grep -q 'insert_image_data_undo_redo_restores_asset_and_block' "$ROOT/crates/turkuaz-office-writer/tests/writer_domain_tests.rs"
grep -q 'onPaste' "$ROOT/apps/desktop/src/views/writer-paragraph.tsx"
grep -q 'onCut' "$ROOT/apps/desktop/src/views/writer-paragraph.tsx"
grep -q 'onCopy' "$ROOT/apps/desktop/src/views/writer-paragraph.tsx"
grep -q 'writer_replace_range_with_styled_runs' "$ROOT/apps/desktop/src-tauri/src/controllers/writer_desktop_controller.rs"
grep -q 'writer_get_asset' "$ROOT/apps/desktop/src-tauri/src/controllers/writer_desktop_controller.rs"
grep -q 'writer_insert_image_data' "$ROOT/apps/desktop/src-tauri/src/controllers/writer_desktop_controller.rs"
grep -q 'WriterImageView' "$ROOT/crates/turkuaz-office-writer/src/views/writer_view.rs"
grep -q 'writerGetAsset' "$ROOT/apps/desktop/src/config/ipc-commands.ts"
grep -q 'class ImageAssetTool' "$ROOT/apps/desktop/src/tools/image-asset.tool.ts"
grep -q 'WriterImageBlock' "$ROOT/apps/desktop/src/views/writer-image.tsx"
grep -q 'replace_range_with_styled_runs_preserves_neighbor_styles_and_undoes_once' "$ROOT/crates/turkuaz-office-writer/tests/writer_domain_tests.rs"
grep -q 'replace_range_with_empty_fragment_keeps_editable_empty_run' "$ROOT/crates/turkuaz-office-writer/tests/writer_domain_tests.rs"


grep -q 'writer_print:' "$ROOT/config/project.yml"
grep -q 'printer_discovery: delegated_to_system_dialog' "$ROOT/config/project.yml"
grep -q 'WRITER_PRINT_PREVIEW_ZOOM_PERCENT' "$ROOT/apps/desktop/src/config/print.ts"
grep -q 'class PrintTool' "$ROOT/apps/desktop/src/tools/print.tool.ts"
grep -q 'window.print' "$ROOT/apps/desktop/src/tools/print.tool.ts"
grep -q 'openPrintPreview' "$ROOT/apps/desktop/src/services/writer-session.service.ts"
grep -q 'printDocument' "$ROOT/apps/desktop/src/controllers/writer.controller.ts"
grep -q 'printPreviewLayout' "$ROOT/apps/desktop/src/repositories/writer-session.repository.ts"
grep -q 'KEYBOARD_KEYS.p' "$ROOT/apps/desktop/src/services/keyboard-shortcut.service.ts"
grep -q 'KEYBOARD_KEYS.escape' "$ROOT/apps/desktop/src/services/keyboard-shortcut.service.ts"
grep -q 'WriterPrintPreview' "$ROOT/apps/desktop/src/views/writer-shell.tsx"
grep -q '@media print' "$ROOT/apps/desktop/src/views/app.css"
grep -q 'maps canonical twip page size to physical print inches' "$ROOT/apps/desktop/src/tools/print.tool.test.ts"



grep -q '"crates/turkuaz-office-format-adapters"' "$ROOT/Cargo.toml"
grep -q '    - format_adapters' "$ROOT/config/project.yml"
grep -q 'writer_docx:' "$ROOT/config/project.yml"
grep -q 'pub struct DocxService' "$ROOT/crates/turkuaz-office-format-adapters/src/services/docx_service.rs"
grep -q 'CompressionMethod::Deflated' "$ROOT/crates/turkuaz-office-format-adapters/src/tools/docx_archive_tool.rs"
grep -q 'DocTypeUnsupported' "$ROOT/crates/turkuaz-office-format-adapters/src/tools/docx_xml_tool.rs"
grep -q 'DocxUnsupportedFeature::Hyperlink' "$ROOT/crates/turkuaz-office-format-adapters/src/tools/docx_xml_tool.rs"
grep -q 'docx_minimum_round_trip_preserves_text_typography_alignment_and_page_geometry' "$ROOT/crates/turkuaz-office-format-adapters/tests/docx_minimum_tests.rs"
grep -q 'load_external_document' "$ROOT/crates/turkuaz-office-writer/src/services/writer_editor_service.rs"
grep -q 'writer_import_docx' "$ROOT/apps/desktop/src-tauri/src/controllers/writer_desktop_controller.rs"
grep -q 'writer_export_docx' "$ROOT/apps/desktop/src-tauri/src/controllers/writer_desktop_controller.rs"
grep -q 'docx_export_import_rekeys_document_and_keeps_native_session_untracked' "$ROOT/apps/desktop/src-tauri/tests/writer_docx_service_tests.rs"
grep -q 'writerImportDocx' "$ROOT/apps/desktop/src/config/ipc-commands.ts"
grep -q 'writerExportDocx' "$ROOT/apps/desktop/src/config/ipc-commands.ts"
grep -q 'importDocx' "$ROOT/apps/desktop/src/services/writer-session.service.ts"
grep -q 'exportDocx' "$ROOT/apps/desktop/src/services/writer-session.service.ts"
grep -q 'WriterDocxCompatibilityBanner' "$ROOT/apps/desktop/src/views/writer-shell.tsx"



grep -q 'writer_pdf:' "$ROOT/config/project.yml"
grep -q 'printpdf = ' "$ROOT/crates/turkuaz-office-format-adapters/Cargo.toml"
grep -q 'pub struct PdfService' "$ROOT/crates/turkuaz-office-format-adapters/src/services/pdf_service.rs"
grep -q 'pub struct PdfWriterTool' "$ROOT/crates/turkuaz-office-format-adapters/src/tools/pdf_writer_tool.rs"
grep -q 'subset_fonts: true' "$ROOT/crates/turkuaz-office-format-adapters/src/tools/pdf_writer_tool.rs"
grep -q 'PDF_TAB_SPACES' "$ROOT/crates/turkuaz-office-format-adapters/src/tools/pdf_writer_tool.rs"
grep -q 'pdf_font_requests_preserve_family_bold_and_italic_variants' "$ROOT/crates/turkuaz-office-format-adapters/tests/pdf_minimum_tests.rs"
grep -q 'pub struct SystemFontTool' "$ROOT/apps/desktop/src-tauri/src/tools/system_font_tool.rs"
grep -q 'pdf_font_fallbacks' "$ROOT/apps/desktop/src-tauri/src/config/pdf_font_config.rs"
grep -q 'load_system_fonts' "$ROOT/apps/desktop/src-tauri/src/tools/system_font_tool.rs"
grep -q 'writer_export_pdf' "$ROOT/apps/desktop/src-tauri/src/controllers/writer_desktop_controller.rs"
grep -q 'writerExportPdf' "$ROOT/apps/desktop/src/config/ipc-commands.ts"
grep -q 'exportPdf' "$ROOT/apps/desktop/src/services/writer-session.service.ts"
grep -q 'pdf_export_writes_pdf_signature_and_keeps_native_session_untracked' "$ROOT/apps/desktop/src-tauri/tests/writer_pdf_service_tests.rs"



grep -q 'desktop_recent_files:' "$ROOT/config/project.yml"
grep -q 'path_normalization: canonical' "$ROOT/config/project.yml"
grep -q 'RECENT_FILES_MAX_ENTRIES' "$ROOT/apps/desktop/src-tauri/src/config/constants.rs"
grep -q 'pub struct AppStatePathTool' "$ROOT/apps/desktop/src-tauri/src/tools/app_state_path_tool.rs"
grep -q 'canonicalize_file' "$ROOT/apps/desktop/src-tauri/src/tools/local_file_tool.rs"
grep -q 'pub struct RecentFilesRepository' "$ROOT/apps/desktop/src-tauri/src/repositories/recent_files_repository.rs"
grep -q 'pub struct RecentFilesService' "$ROOT/apps/desktop/src-tauri/src/services/recent_files_service.rs"
grep -q 'writer_list_recent_files' "$ROOT/apps/desktop/src-tauri/src/controllers/writer_desktop_controller.rs"
grep -q 'writer_record_recent_file' "$ROOT/apps/desktop/src-tauri/src/controllers/writer_desktop_controller.rs"
grep -q 'writerListRecentFiles' "$ROOT/apps/desktop/src/config/ipc-commands.ts"
grep -q 'writerRecordRecentFile' "$ROOT/apps/desktop/src/config/ipc-commands.ts"
grep -q 'openRecentFile' "$ROOT/apps/desktop/src/services/writer-session.service.ts"
grep -q 'recordRecentFile' "$ROOT/apps/desktop/src/services/writer-session.service.ts"
grep -q 'RECENT_FILES_RIBBON_LIMIT' "$ROOT/apps/desktop/src/views/writer-ribbon.tsx"
grep -q 'recent_files_are_canonical_deduplicated_limited_and_pruned' "$ROOT/apps/desktop/src-tauri/tests/recent_files_service_tests.rs"
grep -q 'recent_record_does_not_change_native_file_session' "$ROOT/apps/desktop/src-tauri/tests/writer_recent_files_integration_tests.rs"



grep -q 'desktop_file_associations:' "$ROOT/config/project.yml"
grep -q 'running_instance_handoff: false' "$ROOT/config/project.yml"
grep -q 'fileAssociations' "$ROOT/apps/desktop/src-tauri/tauri.conf.json5"
grep -q 'application/x-turkuaz-office' "$ROOT/apps/desktop/src-tauri/tauri.conf.json5"
grep -q '"tauri:build:windows": "tauri build --bundles nsis"' "$ROOT/apps/desktop/package.json"
grep -q '"tauri:build:linux": "tauri build --bundles deb,appimage"' "$ROOT/apps/desktop/package.json"
grep -q 'pub struct StartupArgumentsTool' "$ROOT/apps/desktop/src-tauri/src/tools/startup_arguments_tool.rs"
grep -q 'pub struct StartupFileService' "$ROOT/apps/desktop/src-tauri/src/services/startup_file_service.rs"
grep -q 'LocalFileTool::canonicalize_file' "$ROOT/apps/desktop/src-tauri/src/services/startup_file_service.rs"
grep -q 'writer_take_startup_file' "$ROOT/apps/desktop/src-tauri/src/controllers/writer_desktop_controller.rs"
grep -q 'writerTakeStartupFile' "$ROOT/apps/desktop/src/config/ipc-commands.ts"
grep -q 'takeStartupFile' "$ROOT/apps/desktop/src/tools/tauri-writer.tool.ts"
grep -q 'openNativePath(startupPath)' "$ROOT/apps/desktop/src/services/writer-session.service.ts"
grep -q 'startup_file_service_selects_first_existing_tko_once' "$ROOT/apps/desktop/src-tauri/tests/startup_file_service_tests.rs"
grep -q 'writer_desktop_exposes_startup_file_as_one_shot_state' "$ROOT/apps/desktop/src-tauri/tests/startup_file_service_tests.rs"



grep -q 'writer_templates:' "$ROOT/config/project.yml"
grep -q 'source: built_in_yaml' "$ROOT/config/project.yml"
grep -q 'catalog_version: 1' "$ROOT/crates/turkuaz-office-writer/templates/builtin.yml"
grep -q 'quick_create: true' "$ROOT/crates/turkuaz-office-writer/templates/builtin.yml"
grep -q 'pub struct WriterTemplateCatalogTool' "$ROOT/crates/turkuaz-office-writer/src/tools/writer_template_catalog_tool.rs"
grep -q 'pub struct WriterTemplateService' "$ROOT/crates/turkuaz-office-writer/src/services/writer_template_service.rs"
grep -q 'create_document_from_template' "$ROOT/crates/turkuaz-office-writer/src/services/writer_editor_service.rs"
grep -q 'built_in_template_catalog_is_stable_and_ordered' "$ROOT/crates/turkuaz-office-writer/tests/writer_template_tests.rs"
grep -q 'report_template_creates_canonical_styled_paragraphs' "$ROOT/crates/turkuaz-office-writer/tests/writer_template_tests.rs"
grep -q 'writer_list_templates' "$ROOT/apps/desktop/src-tauri/src/controllers/writer_desktop_controller.rs"
grep -q 'writer_create_document_from_template' "$ROOT/apps/desktop/src-tauri/src/controllers/writer_desktop_controller.rs"
grep -q 'writerListTemplates' "$ROOT/apps/desktop/src/config/ipc-commands.ts"
grep -q 'writerCreateDocumentFromTemplate' "$ROOT/apps/desktop/src/config/ipc-commands.ts"
grep -q 'refreshTemplates' "$ROOT/apps/desktop/src/services/writer-session.service.ts"
grep -q 'createDocumentFromTemplate' "$ROOT/apps/desktop/src/controllers/writer.controller.ts"
grep -q 'item.quickCreate' "$ROOT/apps/desktop/src/views/writer-ribbon.tsx"
grep -q 'desktop_template_catalog_and_create_keep_native_session_untracked' "$ROOT/apps/desktop/src-tauri/tests/writer_template_desktop_tests.rs"



grep -q 'desktop_localization:' "$ROOT/config/project.yml"
grep -q 'default_locale: tr-TR' "$ROOT/config/project.yml"
grep -q 'en-US' "$ROOT/config/project.yml"
grep -q 'DESKTOP_LOCALES = \["tr-TR", "en-US"\]' "$ROOT/apps/desktop/src/config/localization.ts"
grep -q 'export const EN_LABELS' "$ROOT/apps/desktop/src/language/en.ts"
grep -q 'export const TR_LABELS' "$ROOT/apps/desktop/src/language/tr.ts"
grep -q 'DESKTOP_LANGUAGE_PACKS' "$ROOT/apps/desktop/src/language/language-packs.ts"
grep -q 'createSignal' "$ROOT/apps/desktop/src/language/language-service.ts"
grep -q 'class LanguagePreferenceTool' "$ROOT/apps/desktop/src/tools/language-preference.tool.ts"
grep -q 'browserStorage' "$ROOT/apps/desktop/src/tools/language-preference.tool.ts"
grep -q 'class LanguagePreferenceService' "$ROOT/apps/desktop/src/services/language-preference.service.ts"
grep -q 'setLocale(locale: string)' "$ROOT/apps/desktop/src/controllers/writer.controller.ts"
grep -q 'writer-statusbar__language' "$ROOT/apps/desktop/src/views/writer-statusbar.tsx"
grep -q 'switches between Turkish and English packs at runtime' "$ROOT/apps/desktop/src/language/language-service.test.ts"
grep -q 'loads persisted English locale and saves later changes' "$ROOT/apps/desktop/src/services/language-preference.service.test.ts"
grep -q 'keeps Writer usable when preference storage throws' "$ROOT/apps/desktop/src/services/language-preference.service.test.ts"



grep -q 'desktop_keyboard_smoke:' "$ROOT/config/project.yml"
grep -q 'typed_shortcut_resolver: true' "$ROOT/config/project.yml"
grep -q 'WRITER_SHORTCUT_ACTIONS' "$ROOT/apps/desktop/src/config/keyboard.ts"
grep -q 'WRITER_ARIA_SHORTCUTS' "$ROOT/apps/desktop/src/config/keyboard.ts"
grep -q 'class KeyboardShortcutService' "$ROOT/apps/desktop/src/services/keyboard-shortcut.service.ts"
grep -q 'resolveKeyboardShortcut' "$ROOT/apps/desktop/src/controllers/writer.controller.ts"
grep -q 'WRITER_SHORTCUT_ACTIONS.closePrintPreview' "$ROOT/apps/desktop/src/views/writer-shell.tsx"
grep -q 'aria-keyshortcuts={WRITER_ARIA_SHORTCUTS.newDocument}' "$ROOT/apps/desktop/src/views/writer-ribbon.tsx"
grep -q 'aria-keyshortcuts={WRITER_ARIA_SHORTCUTS.zoomReset}' "$ROOT/apps/desktop/src/views/writer-statusbar.tsx"
grep -q 'writer-paragraph:focus-visible' "$ROOT/apps/desktop/src/views/app.css"
grep -q 'statusbar-button:focus-visible' "$ROOT/apps/desktop/src/views/app.css"
grep -q 'maps Ctrl+%s to %s' "$ROOT/apps/desktop/src/services/keyboard-shortcut.service.test.ts"
grep -q 'blocks edit shortcuts during IME composition' "$ROOT/apps/desktop/src/services/keyboard-shortcut.service.test.ts"
grep -q 'restricts print preview shortcuts to Escape and print' "$ROOT/apps/desktop/src/services/keyboard-shortcut.service.test.ts"



grep -q 'sheet_cell_model:' "$ROOT/config/project.yml"
grep -q 'storage: sparse' "$ROOT/config/project.yml"
grep -q 'max_rows: 1048576' "$ROOT/config/project.yml"
grep -q 'max_columns: 16384' "$ROOT/config/project.yml"
grep -q 'pub struct CellAddress' "$ROOT/crates/turkuaz-office-sheet/src/services/sheet_types.rs"
grep -q 'pub enum CellValue' "$ROOT/crates/turkuaz-office-sheet/src/services/sheet_types.rs"
grep -q 'BTreeMap<CellAddress, CellValue>' "$ROOT/crates/turkuaz-office-sheet/src/services/sheet_types.rs"
grep -q 'pub struct SheetService' "$ROOT/crates/turkuaz-office-sheet/src/services/sheet_service.rs"
grep -q 'set_cell_by_a1' "$ROOT/crates/turkuaz-office-sheet/src/services/sheet_service.rs"
grep -q 'pub trait SheetDocumentRepository' "$ROOT/crates/turkuaz-office-sheet/src/repositories/sheet_document_repository.rs"
grep -q 'pub struct CellReferenceTool' "$ROOT/crates/turkuaz-office-sheet/src/tools/cell_reference_tool.rs"
grep -q 'pub struct SheetController' "$ROOT/crates/turkuaz-office-sheet/src/controllers/sheet_controller.rs"
grep -q 'pub struct SheetDocumentView' "$ROOT/crates/turkuaz-office-sheet/src/views/sheet_view.rs"
grep -q 'a1_reference_tool_parses_and_formats_grid_boundaries' "$ROOT/crates/turkuaz-office-sheet/tests/sheet_cell_model_tests.rs"
grep -q 'sparse_set_get_and_clear_mutate_revision_only_when_data_changes' "$ROOT/crates/turkuaz-office-sheet/tests/sheet_cell_model_tests.rs"

for sheet_file in   "$ROOT/crates/turkuaz-office-sheet/Cargo.toml"   "$ROOT/crates/turkuaz-office-sheet/src/lib.rs"   "$ROOT/crates/turkuaz-office-sheet/src/config/constants.rs"   "$ROOT/crates/turkuaz-office-sheet/src/controllers/sheet_controller.rs"   "$ROOT/crates/turkuaz-office-sheet/src/services/sheet_types.rs"   "$ROOT/crates/turkuaz-office-sheet/src/services/sheet_service.rs"   "$ROOT/crates/turkuaz-office-sheet/src/repositories/sheet_document_repository.rs"   "$ROOT/crates/turkuaz-office-sheet/src/tools/cell_reference_tool.rs"   "$ROOT/crates/turkuaz-office-sheet/src/tools/sheet_id_tool.rs"   "$ROOT/crates/turkuaz-office-sheet/src/views/sheet_view.rs"   "$ROOT/crates/turkuaz-office-sheet/src/language/mod.rs"   "$ROOT/crates/turkuaz-office-sheet/tests/sheet_cell_model_tests.rs"; do
  grep -q "Version: $SHEET_MODULE_VERSION" "$sheet_file"
done



grep -q 'sheet_csv_xlsx:' "$ROOT/config/project.yml"
grep -q 'import_semantics: text_only' "$ROOT/config/project.yml"
grep -q 'formula_import: strict_reject' "$ROOT/config/project.yml"
grep -q 'turkuaz-office-sheet = ' "$ROOT/crates/turkuaz-office-format-adapters/Cargo.toml"
grep -q 'pub struct SheetCsvTool' "$ROOT/crates/turkuaz-office-format-adapters/src/tools/sheet_csv_tool.rs"
grep -q 'pub struct SheetCsvService' "$ROOT/crates/turkuaz-office-format-adapters/src/services/sheet_csv_service.rs"
grep -q 'pub struct SheetXlsxArchiveTool' "$ROOT/crates/turkuaz-office-format-adapters/src/tools/sheet_xlsx_archive_tool.rs"
grep -q 'pub struct SheetXlsxXmlTool' "$ROOT/crates/turkuaz-office-format-adapters/src/tools/sheet_xlsx_xml_tool.rs"
grep -q 'pub struct SheetXlsxService' "$ROOT/crates/turkuaz-office-format-adapters/src/services/sheet_xlsx_service.rs"
grep -q 'validate_root_relationships' "$ROOT/crates/turkuaz-office-format-adapters/src/tools/sheet_xlsx_xml_tool.rs"
grep -q 'UnsupportedFormula' "$ROOT/crates/turkuaz-office-format-adapters/src/services/sheet_xlsx_service.rs"
grep -q 'csv_parser_handles_quotes_crlf_and_service_import_is_text_only' "$ROOT/crates/turkuaz-office-format-adapters/tests/sheet_csv_xlsx_tests.rs"
grep -q 'csv_sparse_export_handles_max_grid_address_without_rectangular_allocation' "$ROOT/crates/turkuaz-office-format-adapters/tests/sheet_csv_xlsx_tests.rs"
grep -q 'xlsx_round_trip_preserves_multi_sheet_text_number_and_boolean_values' "$ROOT/crates/turkuaz-office-format-adapters/tests/sheet_csv_xlsx_tests.rs"
grep -q 'xlsx_import_reads_shared_string_cells' "$ROOT/crates/turkuaz-office-format-adapters/tests/sheet_csv_xlsx_tests.rs"
grep -q 'xlsx_import_rejects_missing_root_workbook_relationship' "$ROOT/crates/turkuaz-office-format-adapters/tests/sheet_csv_xlsx_tests.rs"
grep -q 'xlsx_export_rejects_duplicate_worksheet_names_case_insensitively' "$ROOT/crates/turkuaz-office-format-adapters/tests/sheet_csv_xlsx_tests.rs"
grep -q 'xlsx_export_rejects_xml_invalid_cell_text' "$ROOT/crates/turkuaz-office-format-adapters/tests/sheet_csv_xlsx_tests.rs"
grep -q 'xlsx_import_rejects_formula_cells_until_adapter_formula_profile' "$ROOT/crates/turkuaz-office-format-adapters/tests/sheet_csv_xlsx_tests.rs"
grep -q 'csv_and_xlsx_export_reject_canonical_formula_until_adapter_formula_profile' "$ROOT/crates/turkuaz-office-format-adapters/tests/sheet_csv_xlsx_tests.rs"

for sheet_format_file in \
  "$ROOT/crates/turkuaz-office-format-adapters/Cargo.toml" \
  "$ROOT/crates/turkuaz-office-format-adapters/src/config/sheet_constants.rs" \
  "$ROOT/crates/turkuaz-office-format-adapters/src/models/sheet_xlsx_model.rs" \
  "$ROOT/crates/turkuaz-office-format-adapters/src/services/sheet_csv_service.rs" \
  "$ROOT/crates/turkuaz-office-format-adapters/src/services/sheet_xlsx_service.rs" \
  "$ROOT/crates/turkuaz-office-format-adapters/src/tools/sheet_csv_tool.rs" \
  "$ROOT/crates/turkuaz-office-format-adapters/src/tools/sheet_xlsx_archive_tool.rs" \
  "$ROOT/crates/turkuaz-office-format-adapters/src/tools/sheet_xlsx_xml_tool.rs" \
  "$ROOT/crates/turkuaz-office-format-adapters/tests/sheet_csv_xlsx_tests.rs"; do
  grep -q "Version: $SHEET_MODULE_VERSION" "$sheet_format_file"
done

grep -q 'sheet_formula_engine:' "$ROOT/config/project.yml"
grep -q 'formula_engine: true' "$ROOT/config/project.yml"
grep -q 'pub struct FormulaCell' "$ROOT/crates/turkuaz-office-sheet/src/services/sheet_types.rs"
grep -q 'pub struct FormulaTool' "$ROOT/crates/turkuaz-office-sheet/src/tools/formula_tool.rs"
grep -q 'MAX_FORMULA_PARSE_DEPTH' "$ROOT/crates/turkuaz-office-sheet/src/config/constants.rs"
grep -q 'MAX_FORMULA_OPERATIONS' "$ROOT/crates/turkuaz-office-sheet/src/config/constants.rs"
grep -q 'TooComplex' "$ROOT/crates/turkuaz-office-sheet/src/tools/formula_tool.rs"
grep -q 'pub fn set_formula_by_a1' "$ROOT/crates/turkuaz-office-sheet/src/services/sheet_service.rs"
grep -q 'FormulaCycle' "$ROOT/crates/turkuaz-office-sheet/src/services/sheet_service.rs"
grep -q 'pub fn evaluated_cell_by_a1' "$ROOT/crates/turkuaz-office-sheet/src/services/sheet_service.rs"
grep -q 'CellValue::Formula' "$ROOT/crates/turkuaz-office-format-adapters/src/services/sheet_csv_service.rs"
grep -q 'CellValue::Formula' "$ROOT/crates/turkuaz-office-format-adapters/src/services/sheet_xlsx_service.rs"
grep -q 'formula_evaluation_respects_operator_precedence_and_revision_no_op' "$ROOT/crates/turkuaz-office-sheet/tests/sheet_formula_engine_tests.rs"
grep -q 'formula_cycle_division_and_non_numeric_reference_are_typed_errors' "$ROOT/crates/turkuaz-office-sheet/tests/sheet_formula_engine_tests.rs"



grep -q 'sheet_format_filter_sort:' "$ROOT/config/project.yml"
grep -q 'max_query_rows: 100000' "$ROOT/config/project.yml"
grep -q 'pub struct CellFormat' "$ROOT/crates/turkuaz-office-sheet/src/services/sheet_types.rs"
grep -q 'pub enum SheetFilterCondition' "$ROOT/crates/turkuaz-office-sheet/src/services/sheet_types.rs"
grep -q 'pub struct SheetRange' "$ROOT/crates/turkuaz-office-sheet/src/services/sheet_types.rs"
grep -q 'MAX_CELL_DECIMAL_PLACES' "$ROOT/crates/turkuaz-office-sheet/src/config/constants.rs"
grep -q 'MAX_SHEET_QUERY_ROWS' "$ROOT/crates/turkuaz-office-sheet/src/config/constants.rs"
grep -q 'pub fn set_cell_format_by_a1' "$ROOT/crates/turkuaz-office-sheet/src/services/sheet_service.rs"
grep -q 'pub fn query_rows' "$ROOT/crates/turkuaz-office-sheet/src/services/sheet_service.rs"
grep -q 'pub struct CellFormatView' "$ROOT/crates/turkuaz-office-sheet/src/views/sheet_view.rs"
grep -q 'cell_format_is_canonical_sparse_and_revision_aware' "$ROOT/crates/turkuaz-office-sheet/tests/sheet_format_filter_sort_tests.rs"
grep -q 'filter_and_sort_query_is_formula_aware_and_does_not_mutate_document' "$ROOT/crates/turkuaz-office-sheet/tests/sheet_format_filter_sort_tests.rs"



grep -q 'sheet_basic_charts:' "$ROOT/config/project.yml"
grep -q 'max_points: 1000' "$ROOT/config/project.yml"
grep -q 'pub struct ChartId' "$ROOT/crates/turkuaz-office-sheet/src/services/sheet_types.rs"
grep -q 'pub enum ChartType' "$ROOT/crates/turkuaz-office-sheet/src/services/sheet_types.rs"
grep -q 'pub struct SheetChart' "$ROOT/crates/turkuaz-office-sheet/src/services/sheet_types.rs"
grep -q 'pub struct ChartDataPoint' "$ROOT/crates/turkuaz-office-sheet/src/services/sheet_types.rs"
grep -q 'CHART_ID_PREFIX' "$ROOT/crates/turkuaz-office-sheet/src/config/constants.rs"
grep -q 'MAX_CHART_POINTS' "$ROOT/crates/turkuaz-office-sheet/src/config/constants.rs"
grep -q 'fn next_chart_id' "$ROOT/crates/turkuaz-office-sheet/src/tools/sheet_id_tool.rs"
grep -q 'pub fn create_chart' "$ROOT/crates/turkuaz-office-sheet/src/services/sheet_service.rs"
grep -q 'pub fn chart_data' "$ROOT/crates/turkuaz-office-sheet/src/services/sheet_service.rs"
grep -q 'pub struct ChartDataView' "$ROOT/crates/turkuaz-office-sheet/src/views/sheet_view.rs"
grep -q 'chart_creation_is_canonical_and_revision_aware' "$ROOT/crates/turkuaz-office-sheet/tests/sheet_basic_charts_tests.rs"
grep -q 'chart_data_supports_formula_values' "$ROOT/crates/turkuaz-office-sheet/tests/sheet_basic_charts_tests.rs"



grep -q 'sheet_100k_benchmark:' "$ROOT/config/project.yml"
grep -q 'cell_count: 100000' "$ROOT/config/project.yml"
grep -q 'fixed_ci_latency_threshold: false' "$ROOT/config/project.yml"
grep -q 'const BENCHMARK_CELL_COUNT: u32 = 100_000' "$ROOT/crates/turkuaz-office-sheet/tests/sheet_100k_benchmark.rs"
grep -q 'benchmark_100k_sparse_build_and_view_projection' "$ROOT/crates/turkuaz-office-sheet/tests/sheet_100k_benchmark.rs"
grep -q 'benchmark_100k_sorted_row_query' "$ROOT/crates/turkuaz-office-sheet/tests/sheet_100k_benchmark.rs"
grep -q '#\[ignore = "performance profile; run explicitly with --ignored --nocapture"\]' "$ROOT/crates/turkuaz-office-sheet/tests/sheet_100k_benchmark.rs"
grep -q 'M2 feature kapsaminda planlanan alt fazlar tamamlandi' "$ROOT/docs/05-roadmap/roadmap.md"

echo "Turkuaz Office v0.3.1 Community Preview contract verification BASARILI."
